[profile.default]
src = 'src'
test = 'test'
script = 'script'
out = 'out'
libs = ['lib']
cache_path = 'cache'
solc = "0.8.30"
via_ir = true
optimizer = true
optimizer_runs = 200


# For dependencies
remappings = [
    '@filecoin-pay/=lib/filecoin-pay/src/',
    '@filecoin-services/=lib/filecoin-services/service_contracts/src/',
    '@pdp/=lib/filecoin-services/service_contracts/lib/pdp/src/',
    '@session-key-registry/=lib/filecoin-services/service_contracts/lib/session-key-registry/src/',
    '@openzeppelin/contracts-upgradeable/=lib/filecoin-services/service_contracts/lib/openzeppelin-contracts-upgradeable/contracts/',
    '@fws-payments/=lib/filecoin-services/service_contracts/lib/fws-payments/src/',
    '@fvm-solidity/=lib/filecoin-services/service_contracts/lib/fws-payments/lib/fvm-solidity/src/'
]
